### ISSUE TITLE
open pdf?

### ISSUE THREAD

**Issue by rhaynes74** [msprev/fzf-bibtex#26]
Hi folks, is it possible to open a pdf associated with a citation?   My bibtex entries all have "file= " entries.    It would be great to have a way to open the pdf from within vim. 

Thanks
RH

**Comment by msprev** [comment]
Yes, this is very easy to add. However, there is no standard way of encoding linked PDF files in BibTeX files, so I did not include this kind of functionality in the original package. However, it's very easy to write something that will do it based on your own particular conventions for using 'file='.

fzf-bibtex outputs to stdout a list of bibtex keys for the items that the user has selected. All you need to do is write a short program/script (which could be in any language -- Go, Python, bash, vimscript, whatever) that takes a list of keys plus your bibtex file, finds the 'file=' fields associated with those keys and opens the named files. Because anything one does here will be bespoke to your setup (for the reason above, a general solution is not possible), you don't need to worry too much about robustness in parsing bibtex. All you need is something that works for your own bibtex files. If you want something fancy and more robust, then look at how `bibtex-markdown` does this. To me, that seems overkill for your case. You'll get 99% the behaviour you want just with a script/program that greps your bibtex file with regexs to find and open the named files.

**Comment by rhaynes74** [comment]
Thanks for the response!


We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.
