### ISSUE TITLE
Absolute path for $FZF_BIBTEX_SOURCES from environment var

### ISSUE THREAD

**Issue by folofjc** [msprev/fzf-bibtex#29]
Thanks for this! I have been looking for something like this for a long time, and the fzf integration is great!

Perhaps I have set up incorrectly, but in my `~/.vimrc` I have `$FZF_BIBTEX_SOURCES` as an absolute path via an environment variable, something like:
```
let $FZF_BIBTEX_SOURCES = '$MYBIBDIR/BibTexFiles'
```

When I try to use this in vim via `<leader>c`, I get an error that it cannot find the directory, because it is searching relative to my current directory. So it is looking in `/path/to/current/dir/$MYBIBDIR/BibTexFiles` which does not exist.

If I hard code the absolute path, it works.

**Comment by folofjc** [comment]
I tried to see how to fix this, I guess around [this line](https://github.com/msprev/fzf-bibtex/blob/master/startup/startup.go#L23)? But I don't know `go` so I wasn't sure how to fix is.

**Comment by msprev** [comment]
The issue is that you are treating an environment variable as a string literal in your vimscript expression. fzf-bibtex has no way to know what your intended meaning is. Have a look at this to see how to correct it using expansion and concatenation on $MYBIBDIR to set the variable $FZF_BIBTEX_SOURCES:

- https://vi.stackexchange.com/questions/31329/why-is-let-foo-home-bar-invalid

**Comment by folofjc** [comment]
Ah, okay thanks! I am able to do that in lots of other vim packages, but those are always for variables, not env vars. Sorry, I got confused.
